#
# A type can be one of:
#
$schema: https://qualang.io/2021.1/ast_ext.schema.json#

enums: {}

unions:
  AnalogOutputConfig:
    - AnalogSingleOutputConfig
    - AnalogMixedOutputConfig

  AnalogWaveformConfig:
    - ConstantWaveformConfig
    - ArbitraryWaveformConfig

  AnalogPulseConfig:
    - SinglePulseConfig
    - MixedPulseConfig

types:

  Config:
    analog_outputs: [ AnalogOutputConfig ]
    analog_inputs: [ AnalogInputConfig ]
    digital_outputs: [ DigitalOutputConfig ]
    digital_inputs: [ DigitalInputConfig ]
    oscillators: [ OscillatorConfig ]
    analog_waveforms: [ AnalogWaveformConfig ]
    analog_pulse: [ AnalogPulseConfig ]
    digital_waveforms: [ DigitalWaveformConfig ]
    digital_route: [ DigitalRouteConfig ]

  AnalogOutputFilterConfig:
    feed_forward: [ number ]
    feed_back: [ number ]

  AnalogOutputPortConfig:
    port: number
    filter: AnalogOutputFilterConfig
    offset: number

  AnalogSingleOutputConfig:
    name: string
    controller: string
    port: AnalogOutputPortConfig

  AnalogMixedOutputConfig:
    name: string
    controller: string
    port_I: AnalogOutputPortConfig
    port_Q: AnalogOutputPortConfig

  AnalogInputConfig:
    name: string
    controller: string
    port: number
    offset: number

  DigitalOutputConfig:
    name: string
    controller: string
    port: number

  DigitalInputConfig:
    name: string
    controller: string
    port: number

  ConstantWaveformConfig:
    name: string
    sample: number

  ArbitraryWaveformConfig:
    name: string
    samples: [number]

  AnalogWaveformReference:
    name: string

  SinglePulseConfig:
    name: string
    waveform: AnalogWaveformReference
    length: number

  MixedPulseConfig:
    name: string
    waveform_I: AnalogWaveformReference
    waveform_Q: AnalogWaveformReference
    length: number

  DigitalWaveformSample:
    value: boolean
    length: number

  DigitalWaveformConfig:
    name: string
    samples: [ DigitalWaveformSample ]

  DigtialWaveformReference:
    name: string

  DigitalRouteConfig:
    name: string
    delay: number
    buffer: number

  CorrectionMatrixConfig:
    v00: number
    v01: number
    v10: number
    v11: number

  OscillatorConfig:
    name: string
    intermediate_frequency: number
    correction_matix: CorrectionMatrixConfig

